package org.apache.turbine.services.schedule;


/**
 * Maps ResultSet rows into JobEntry objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Aug 26 11:56:24 CEST 2014]
 *
 */
public class JobEntryRecordMapper extends BaseJobEntryRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1409046984524L;



}
