package org.apache.turbine.services.schedule;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 24 20:11:00 CET 2011]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class JobEntryPeer
    extends org.apache.turbine.services.schedule.BaseJobEntryPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1295896260045L;

}
