package org.apache.turbine.services.schedule;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Oct 14 14:03:25 CEST 2003]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class JobEntryTorquePeer
    extends org.apache.turbine.services.schedule.BaseJobEntryTorquePeer
{
}
